name: Release

on:
  push:
    branches:
      - 'main'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.RELEASE_TOKEN }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json

      - name: Install dependencies
        run: npm install

      - name: Build the application
        run: npm run build

      - name: Distribute app as ZIP file
        run: |
          mv ./dist ./${{ github.event.repository.name }}
          zip -r ${{ github.event.repository.name }}.zip ./${{ github.event.repository.name }}

      - name: Release app
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.run_id }}
          artifacts: "./${{ github.event.repository.name }}.zip"
